import arcade
import random

colores_arcade = [
    'BLACK', 'WHITE', 'ALABASTER', 'BABY_BLUE', 'BEIGE', 'BISTRE_BROWN', 'BLIZZARD_BLUE', 'BLOND', 'BLUE', 'BLUE_BELL',
    'BLUE_GRAY', 'BRASS', 'BRIGHT_GREEN', 'BRONZE_YELLOW', 'BROWN', 'BURNT_ORANGE', 'BURNT_SIENNA', 'BURNT_UMBER',
    'CADET_BLUE', 'CARDINAL', 'CARMINE_RED', 'CARROT_ORANGE', 'CELESTE', 'CERISE', 'CHARCOAL', 'CHARTREUSE', 'CHERRY',
    'CHOCOLATE', 'CINNAMON', 'CINEREOUS', 'CINNABAR', 'CITRINE', 'COBALT_BLUE', 'COFFEE', 'COLUMBIA_BLUE', 'COOL_GREY',
    'COPPER_RED', 'CORAL_PINK', 'CORAL', 'CORNFLOWER_BLUE', 'COSMIC_COBALT', 'COSMIC_LATTE', 'COTTON_CANDY', 'CRANBERRY',
    'CREAM', 'CRIMSON_RED', 'CYAN', 'DARK_BLUE_GRAY', 'DARK_BROWN', 'DARK_BYZANTIUM', 'DARK_CANDY_APPLE_RED', 'DARK_CERULEAN',
    'DARK_CHESTNUT', 'DARK_CORAL', 'DARK_CYAN', 'DARK_ELECTRIC_BLUE', 'DARK_GOLDENROD', 'DARK_GRAY', 'DARK_GREEN', 'DARK_IMPERIAL_BLUE',
    'DARK_JUNGLE_GREEN', 'DARK_KHAKI', 'DARK_LAVA', 'DARK_LIVER', 'DARK_MAGENTA', 'DARK_MIDNIGHT_BLUE', 'DARK_MOSS_GREEN',
    'DARK_OLIVE_GREEN', 'DARK_ORANGE', 'DARK_ORCHID', 'DARK_PASTEL_GREEN', 'DARK_PASTEL_PURPLE', 'DARK_PASTEL_RED', 'DARK_PINK',
    'DARK_POWDER_BLUE', 'DARK_RASPBERRY', 'DARK_RED', 'DARK_SALMON', 'DARK_SCARLET', 'DARK_SEA_GREEN', 'DARK_SIENNA',
    'DARK_SKY_BLUE', 'DARK_SLATE_BLUE', 'DARK_SPRING_GREEN', 'DARK_TAN', 'DARK_TANGERINE', 'DARK_TAUPE', 'DARK_TERRA_COTTA',
    'DARK_TURQUOISE', 'DARK_VANILLA', 'DARK_VIOLET', 'DARK_YELLOW', 'DEEP_AMETHYST', 'DEEP_CARMINE', 'DEEP_CARMINE_PINK',
    'DEEP_CARROT_ORANGE', 'DEEP_CERISE', 'DEEP_CHAMPAGNE', 'DEEP_CHESTNUT', 'DEEP_COFFEE', 'DEEP_FUCHSIA', 'DEEP_GREEN',
    'DEEP_IMPERIAL_BLUE', 'DEEP_JUNGLE_GREEN', 'DEEP_LEMON', 'DEEP_LILAC', 'DEEP_MAGENTA', 'DEEP_PEACH', 'DEEP_PINK',
    'DEEP_RUBY', 'DEEP_SAFFRON', 'DEEP_SKY_BLUE', 'DEEP_SPACE_SPARKLE', 'DEEP_TAUPE', 'DEEP_TUSCAN_RED', 'DEER', 'DENIM',
    'DESERT', 'DESERT_SAND', 'DIM_GRAY', 'DODGER_BLUE', 'DOGWOOD_ROSE', 'DRAB', 'DUKE_BLUE', 'DUTCH_WHITE', 'EARTH_YELLOW',
    'EBONY', 'ECRU', 'EGGPLANT', 'EGGSHELL', 'EGYPTIAN_BLUE', 'ELECTRIC_BLUE', 'ELECTRIC_CRIMSON', 'ELECTRIC_CYAN',
    'ELECTRIC_GREEN', 'ELECTRIC_INDIGO', 'ELECTRIC_LAVENDER', 'ELECTRIC_LIME', 'ELECTRIC_PURPLE', 'ELECTRIC_ULTRAMARINE',
    'ELECTRIC_VIOLET', 'ELECTRIC_YELLOW', 'EMERALD', 'EUCALYPTUS', 'FALLOW', 'FALU_RED', 'FANDANGO', 'FASHION_FUCHSIA',
    'FAWN', 'FELDGRAU', 'FERN_GREEN', 'FIELD_DRAB', 'FIERY_ROSE', 'FIREBRICK', 'FLAME', 'FLAMINGO_PINK', 'FLATTERY',
    'FLAX', 'FLIRT', 'FLORAL_WHITE', 'FLUORESCENT_BLUE', 'FOREST_GREEN', 'FRENCH_BEIGE', 'FRENCH_BLUE', 'FRENCH_FUCHSIA',
    'FRENCH_LILAC', 'FRENCH_LIME', 'FRENCH_MAUVE', 'FRENCH_PINK', 'FRENCH_RASPBERRY', 'FRENCH_ROSE', 'FRENCH_SKY_BLUE',
    'FRENCH_VIOLET', 'FRENCH_WINE', 'FROSTBITE', 'FUCHSIA_PINK', 'FUCHSIA_PURPLE', 'FUCHSIA_ROSE', 'FULVOUS', 'FUNKY_PINK',
    'FUZZY_WUZZY', 'GAMBOGE', 'GARGOYLE_GAS', 'GENERIC_VIRIDIAN', 'GHOST_WHITE', 'GIANTS_CLUB', 'GIRLSENSE', 'GLAUCOUS',
    'GLOSSY_GRAPE', 'GO_GREEN', 'GOLD', 'GOLDEN_BROWN', 'GOLDEN_POPPY', 'GOLDEN_YELLOW', 'GOLDENROD', 'GRANNY_SMITH_APPLE',
    'GRAPE', 'GRAY', 'GREEN', 'GREEN_BLUE', 'GREEN_CYAN', 'GREEN_LIZARD', 'GREEN_SHEEN', 'GREEN_YELLOW', 'GRIFFIN', 'GRIS',
    'GRIZZLY', 'GRULLO', 'GUPPIE_GREEN', 'HALAYA_UBE', 'HALF_BAKED', 'HAN_BLUE', 'HAN_PURPLE', 'HANSA_YELLOW', 'HARLEQUIN',
    'HARVEST_GOLD', 'HEART_GOLD', 'HEAT_WAVE', 'HELIOTROPE', 'HELIOTROPE_GRAY', 'HOLLYWOOD_CERISE', 'HONEYDEW', 'HONOLULU_BLUE',
    'HOOKER_GREEN', 'HOT_MAGENTA', 'HOT_PINK', 'HUNTER_GREEN', 'ICEBERG', 'ICHTHYOSAURS', 'ICTERINE', 'ILLUMINATING_EMERALD',
    'IMPERIAL_RED'
]

color = random.choice(colores_arcade)

arcade.open_window(600,600, "Pantalla de dibujo")

arcade.set_background_color(arcade.color.DAVY_GREY)
arcade.start_render()

arcade.draw_rectangle_filled(300,100,600,280, arcade.color.COOL_BLACK)

arcade.draw_rectangle_filled(100,400,300,200, arcade.color.SEAL_BROWN)
arcade.draw_rectangle_filled(100,400,260,160, arcade.color.VIVID_SKY_BLUE)
arcade.draw_rectangle_filled(100,400,300,10, arcade.color.SEAL_BROWN)
arcade.draw_rectangle_filled(115,400,10,200, arcade.color.SEAL_BROWN)


arcade.draw_circle_filled(175,450,20,arcade.color.WHITE)
arcade.draw_circle_filled(195,445,17,arcade.color.WHITE)
arcade.draw_circle_filled(155,445,17,arcade.color.WHITE)
arcade.draw_rectangle_filled(175,438,30,20,arcade.color.WHITE)

arcade.draw_circle_filled(45,450,20,arcade.color.WHITE)
arcade.draw_circle_filled(65,445,17,arcade.color.WHITE)
arcade.draw_circle_filled(25,445,17,arcade.color.WHITE)
arcade.draw_rectangle_filled(45,438,30,20,arcade.color.WHITE)

arcade.draw_rectangle_filled(600,250,50,100,arcade.color.SEAL_BROWN)
arcade.draw_triangle_filled(600,375,450,300,600,300, arcade.color.UP_FOREST_GREEN)
arcade.draw_triangle_filled(600,425,475,350,600,350, arcade.color.UP_FOREST_GREEN)
arcade.draw_triangle_filled(600,475,500,400,600,400, arcade.color.UP_FOREST_GREEN)
arcade.draw_triangle_filled(600,525,525,450,600,450, arcade.color.UP_FOREST_GREEN)

coordenadas = [
    (574, 367), (530, 308), (493, 330), (558, 321), (583, 313),
    (561, 316), (490, 362), (473, 342), (562, 375), (483, 322),
    (566, 323), (561, 323), (581, 353), (571, 336), (529, 325),
    (477, 324), (563, 332), (540, 326), (484, 324), (563, 363),
    (526, 319), (528, 330), (560, 343), (485, 335), (484, 357),
    (561, 339), (580, 358), (482, 342), (493, 351), (545, 313),
    (569, 354), (479, 358), (567, 316), (493, 320), (488, 341),
    (543, 317), (561, 318), (557, 331), (570, 331), (563, 359)
]
for x, y in coordenadas:
    arcade.draw_circle_filled(x,y,5, arcade.color.color)
arcade.finish_render()
arcade.run()